In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn.preprocessing as prep

In [2]:
#Reading the data from the directory
train = pd.read_csv("C:/Machine Learning/Hackathons/Kaggle/House Price/train.csv")
test = pd.read_csv("C:/Machine Learning/Hackathons/Kaggle/House Price/test.csv")

In [3]:
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
#Checking the shape of training and test data
train.shape, test.shape

((1460, 81), (1459, 80))

check the dtypes of the dataframe, its help to see if they are classified correctly or not. 

we can also use the df.dtypes. it will give the output as 
Id                 int64

MSSubClass         int64

MSZoning          object

In [ ]:
train.info()

Describe function allow you to see the data( mean, std etc) by dtypes, as bydefault it only shows numbers and floats

In [ ]:
train.describe()

In [ ]:
#train.describe(include=np.number)
train.describe(include=np.object)
#train.describe(include=np.float)

In [ ]:
#plt.figure(figsize=(50,18))
plt.rcParams['figure.figsize'] = [50, 25]
train[int_con].boxplot()

# Boxplot

This will show the boxplot not nicely becuase of the variation in the data values for each column, so we can use the 
the normalization or standardization to bring all variables on the same scale.

•When the box plot is short it implies that much of your data points are similar, since there are many values in a small range

•When the box plot is tall it implies that much of your data points are quite different, since the values are spread over a wide range

•If the median value is closer to the bottom then we know that most of the data has lower values. If the median value is closer to the top then we know that most of the data has higher values. Basically, if the median line is not in the middle of the box then it is an indication of skewed data.

•Are the whiskers very long? That means your data has a high standard deviation and variance i.e the values are spread out and highly varying. If you have long whiskers on one side of the box but not the other, then your data may be highly varying only in one direction.

In [ ]:
temp = train[int_con].copy()
temp = (temp - temp.mean())/temp.std()
plt.rcParams['figure.figsize'] = [50, 25]
temp.boxplot()

In [ ]:
#data.groupby('class').hist() - this is to see the distribution by class values
#data.groupby('class').plas.hist(alpha=0.4)This groups the data by class by only plots the histogram of plas 
  ##showing the class value of 0 in red and the class value of 1 in blue. You can see a similar shaped normal 
  ##distribution,but a shift. This attribute is likely going to be useful to discriminate the classes.
train[int_con].hist()

In [ ]:
plt.rcParams['figure.figsize'] = [50, 25]
t = train[int_con].corr()
#diagonal : {‘hist’, ‘kde’} pick between ‘kde’ and ‘hist’ for either Kernel Density Estimation or 
#Histogram plot in the diagonal
pd.plotting.scatter_matrix(t, figsize=(60, 60))
plt.show()

In [ ]:
train.LotArea.describe()

In [ ]:
train.LotArea.quantile([0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1])

In [ ]:
train.LotArea.hist(bins=np.linspace(5000,25000,num=5))

In [ ]:
train.SalePrice.hist()

In [4]:
def dtypes_columns(df):
    int_count = []
    float_count = []
    object_count = []
    other_count = []
    for i in range(len(df.columns)):
        if(df[df.columns[i]].dtypes== "int64"):
            int_count.append(df.columns[i])
        elif(df[df.columns[i]].dtypes== "object"):
            object_count.append(df.columns[i]) 
        elif(df[df.columns[i]].dtypes== "float64"):
            float_count.append(df.columns[i])
        else:
            other_count.append(df.columns[i])
            
    """print(int_count, len(int_count))
    print(float_count, len(float_count))
    print(object_count, len(object_count))"""
    return int_count,float_count,object_count, other_count
a ,b,c,d = dtypes_columns(train)
len(a),len(b),len(c),len(d),

(35, 3, 43, 0)

In [5]:
def missing_count(df,threshold= 0):
    """
    #input: 
        df = dataframe for which we have to calculate the missing counts
        threshold = threshold for the missing count
    #return:
        columns and their missing count percentage"""
    missing  = df.isnull().sum().sort_values(ascending = False)
    return (missing[missing>len(df)*(threshold/100)]/len(df))*100

In [6]:
train.drop(columns=missing_count(train,50).index, inplace=True)

In [7]:
train.shape

(1460, 77)

In [8]:
def fill_missing(df, logic = "mean",threshold = 0):
    df_missing = missing_count(df,threshold)
    #print(df_missing)
    for i in range(len(df_missing)):
        
        if(df[df_missing.index[i]].dtypes== "int64" or df[df_missing.index[i]].dtypes== "float64"):
            #print("int",df_missing.index[i])
            df[df_missing.index[i]].fillna(np.mean(df[df_missing.index[i]]), inplace = True)
        elif(df[df_missing.index[i]].dtypes== "object"):
            df[df_missing.index[i]].fillna(df[df_missing.index[i]].mode()[0], inplace = True)
        else:
            print("other",df_missing.index[i])
    return df
# DataFrame.interpolate need to explore

In [9]:
fill_missing(train)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.000000,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.000000,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.000000,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.000000,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.000000,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000
5,6,50,RL,85.000000,14115,Pave,IR1,Lvl,AllPub,Inside,...,0,320,0,0,700,10,2009,WD,Normal,143000
6,7,20,RL,75.000000,10084,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,8,2007,WD,Normal,307000
7,8,60,RL,70.049958,10382,Pave,IR1,Lvl,AllPub,Corner,...,228,0,0,0,350,11,2009,WD,Normal,200000
8,9,50,RM,51.000000,6120,Pave,Reg,Lvl,AllPub,Inside,...,205,0,0,0,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.000000,7420,Pave,Reg,Lvl,AllPub,Corner,...,0,0,0,0,0,1,2008,WD,Normal,118000
10,11,20,RL,70.000000,11200,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,129500
11,12,60,RL,85.000000,11924,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,7,2006,New,Partial,345000
12,13,20,RL,70.049958,12968,Pave,IR2,Lvl,AllPub,Inside,...,0,0,176,0,0,9,2008,WD,Normal,144000
13,14,20,RL,91.000000,10652,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,8,2007,New,Partial,279500
14,15,20,RL,70.049958,10920,Pave,IR1,Lvl,AllPub,Corner,...,176,0,0,0,0,5,2008,WD,Normal,157000
15,16,45,RM,51.000000,6120,Pave,Reg,Lvl,AllPub,Corner,...,0,0,0,0,0,7,2007,WD,Normal,132000
16,17,20,RL,70.049958,11241,Pave,IR1,Lvl,AllPub,CulDSac,...,0,0,0,0,700,3,2010,WD,Normal,149000
17,18,90,RL,72.000000,10791,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,500,10,2006,WD,Normal,90000
18,19,20,RL,66.000000,13695,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,6,2008,WD,Normal,159000
19,20,20,RL,70.000000,7560,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,5,2009,COD,Abnorml,139000
20,21,60,RL,101.000000,14215,Pave,IR1,Lvl,AllPub,Corner,...,0,0,0,0,0,11,2006,New,Partial,325300
21,22,45,RM,57.000000,7449,Pave,Reg,Bnk,AllPub,Inside,...,205,0,0,0,0,6,2007,WD,Normal,139400
22,23,20,RL,75.000000,9742,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,230000
23,24,120,RM,44.000000,4224,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,6,2007,WD,Normal,129900
24,25,20,RL,70.049958,8246,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,5,2010,WD,Normal,154000
25,26,20,RL,110.000000,14230,Pave,Reg,Lvl,AllPub,Corner,...,0,0,0,0,0,7,2009,WD,Normal,256300
26,27,20,RL,60.000000,7200,Pave,Reg,Lvl,AllPub,Corner,...,0,0,0,0,0,5,2010,WD,Normal,134800
27,28,20,RL,98.000000,11478,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,5,2010,WD,Normal,306000
28,29,20,RL,47.000000,16321,Pave,IR1,Lvl,AllPub,CulDSac,...,0,0,0,0,0,12,2006,WD,Normal,207500
29,30,30,RM,60.000000,6324,Pave,IR1,Lvl,AllPub,Inside,...,87,0,0,0,0,5,2008,WD,Normal,68500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,1431,60,RL,60.000000,21930,Pave,IR3,Lvl,AllPub,Inside,...,0,0,0,0,0,7,2006,WD,Normal,192140
1431,1432,120,RL,70.049958,4928,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,10,2009,WD,Normal,143750
1432,1433,30,RL,60.000000,10800,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,8,2007,WD,Normal,64500
1433,1434,60,RL,93.000000,10261,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,5,2008,WD,Normal,186500
1434,1435,20,RL,80.000000,17400,Pave,Reg,Low,AllPub,Inside,...,0,0,0,0,0,5,2006,WD,Normal,160000
1435,1436,20,RL,80.000000,8400,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,7,2008,COD,Abnorml,174000
1436,1437,20,RL,60.000000,9000,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,120500
1437,1438,20,RL,96.000000,12444,Pave,Reg,Lvl,AllPub,FR2,...,0,304,0,0,0,11,2008,New,Partial,394617
1438,1439,20,RM,90.000000,7407,Pave,Reg,Lvl,AllPub,Inside,...,158,0,0,0,0,4,2010,WD,Normal,149700
1439,1440,60,RL,80.000000,11584,Pave,Reg,Lvl,AllPub,Inside,...,216,0,0,0,0,11,2007,WD,Normal,197000
1440,1441,70,RL,79.000000,11526,Pave,IR1,Bnk,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,191000
1441,1442,120,RM,70.049958,4426,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,5,2008,WD,Normal,149300
1442,1443,60,FV,85.000000,11003,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,4,2009,WD,Normal,310000
1443,1444,30,RL,70.049958,8854,Pave,Reg,Lvl,AllPub,Inside,...,0,0,40,0,0,5,2009,WD,Normal,121000
1444,1445,20,RL,63.000000,8500,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,11,2007,WD,Normal,179600
1445,1446,85,RL,70.000000,8400,Pave,Reg,Lvl,AllPub,Inside,...,252,0,0,0,0,5,2007,WD,Normal,129000
1446,1447,20,RL,70.049958,26142,Pave,IR1,Lvl,AllPub,CulDSac,...,0,0,0,0,0,4,2010,WD,Normal,157900
1447,1448,60,RL,80.000000,10000,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,12,2007,WD,Normal,240000
1448,1449,50,RL,70.000000,11767,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,5,2007,WD,Normal,112000
1449,1450,180,RM,21.000000,1533,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,8,2006,WD,Abnorml,92000
1450,1451,90,RL,60.000000,9000,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,9,2009,WD,Normal,136000
1451,1452,20,RL,78.000000,9262,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,5,2009,New,Partial,287090
1452,1453,180,RM,35.000000,3675,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,5,2006,WD,Normal,145000
1453,1454,20,RL,90.000000,17217,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,7,2006,WD,Abnorml,84500
1454,1455,20,FV,62.000000,7500,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,10,2009,WD,Normal,185000
1455,1456,60,RL,62.000000,7917,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.000000,13175,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.000000,9042,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.000000,9717,Pave,Reg,Lvl,AllPub,Inside,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.000000,9937,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,6,2008,WD,Normal,147500

In [10]:
def outlier_count(df,col_name):
    """
    #input: 
        df = dataframe for which we have to calculate the missing counts
        col_name = name of the column in the dataframe for which we have to calculate the IQR
    #return:
        Count of records"""
    Q75 , Q25 = df[col_name].quantile([.75,.25])
    iqr = Q75 - Q25
    mini = Q25 - (iqr*1.5)
    maxm = Q75 + (iqr*1.5)
    return len(df[(df[col_name] <mini) | (df[col_name] > maxm)])

In [11]:
def outlier_count_df(df):
    outlier_counts = []
    int_con, float_con , _, _=  dtypes_columns(df)
    for i in range(len(int_con)):
        outlier_cnt = []

        #col_na = str(int_con[i])
        count = outlier_count(df,int_con[i])
        outlier_cnt.append(int_con[i])
        outlier_cnt.append(count)
        outlier_counts.append(outlier_cnt)
    for i in range(len(float_con)):
        outlier_cnt = [] 
        #col_na = str(int_con[i])
        count = outlier_count(df,float_con[i])
        outlier_cnt.append(float_con[i])
        outlier_cnt.append(count)
        outlier_counts.append(outlier_cnt)
    return outlier_counts

In [12]:
out_df =  pd.DataFrame(outlier_count_df(test), columns=("Column_name","Outlier_Count"))

In [13]:
def label_counts(df):
    _,_,cat,_ = dtypes_columns(df)
    cat_counts = []
    for i in range(len(cat)):
        for j in range(len(df[cat[i]].value_counts())):
            cat_count = []
            cat_count.append(cat[i])
            cat_count.append(df[cat[i]].value_counts().index[j])
            cat_count.append(df[cat[i]].value_counts().values[j])
            cat_counts.append(cat_count)
    return cat_counts

In [14]:
label_df = pd.DataFrame(label_counts(train), columns=["DF_Col_Name","DF_Col_Lbl","DF_Col_Count"])

In [15]:
#drop_first : bool, default False
#Whether to get k-1 dummies out of k categorical levels by removing the first level.
# logic is that for variable of two labels we need only 1 variable to defince it, 0,1
train_dummies = pd.get_dummies(train, drop_first=True)

In [16]:
train_dummies.shape

(1460, 238)

In [17]:
train_Y =  np.log1p(train["SalePrice"])
train_dummies.drop(columns="SalePrice", inplace=True)

In [18]:
train_Y.head()

0    12.247699
1    12.109016
2    12.317171
3    11.849405
4    12.429220
Name: SalePrice, dtype: float64

In [20]:
train_dummies.shape, train_Y.shape

((1460, 237), (1460,))

In [22]:
from sklearn.model_selection  import train_test_split
train_x,test_train_x,train_y,test_train_y  = train_test_split(train_dummies,train_Y, test_size=0.30, random_state=42)
train_x.shape, train_y.shape, test_train_x.shape, test_train_y.shape

In [ ]:
dt =  DecisionTreeRegressor(max_depth = max_dep, max_features=max_feat,min_samples_leaf=2,max_leaf_nodes=2,
                           random_state=None)
rf = RandomForestRegressor(max_depth=max_dep, max_features=max_feat,n_estimators=1000)
GBoost = GradientBoostingRegressor(n_estimators=3000, learning_rate=0.05,
                                   max_depth=max_dep, max_features=max_feat,
                                   min_samples_leaf=15, min_samples_split=10, 
                                   loss='huber', random_state =5)
model_xgb = xgb.XGBRegressor(colsample_bytree=0.4603, gamma=0.0468, 
                             learning_rate=0.05, max_depth=max_dep, 
                             min_child_weight=1.7817, n_estimators=2200,
                             reg_alpha=0.4640, reg_lambda=0.8571,
                             subsample=0.5213, silent=1,
                             random_state =7, nthread = -1)

In [99]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor,  GradientBoostingRegressor
import xgboost as xgb
from sklearn.grid_search import GridSearchCV

In [128]:
cv_v = 3
max_dep = 6
max_feat = "sqrt"
n_estimat =  300
min_sample_leaf=10
min_sam_spl = 10
dt =  DecisionTreeRegressor(max_depth = max_dep, max_features=max_feat,min_samples_leaf=min_sample_leaf,
                            max_leaf_nodes=2,random_state=None)
rf = RandomForestRegressor(max_depth=max_dep, max_features=max_feat,n_estimators=n_estimat,
                           min_samples_leaf=min_sample_leaf, min_samples_split=min_sam_spl)
GBoost = GradientBoostingRegressor(n_estimators=n_estimat, learning_rate=0.05,
                                   max_depth=max_dep, max_features=max_feat,
                                   min_samples_leaf=min_sample_leaf, min_samples_split=10, 
                                   loss='huber', random_state =5)
model_xgb = xgb.XGBRegressor(colsample_bytree=0.4603, gamma=0.0468, 
                             learning_rate=0.05, max_depth=max_dep, 
                             min_child_weight=1.7817, n_estimators=n_estimat,
                             reg_alpha=0.4640, reg_lambda=0.8571,
                             subsample=0.5213, silent=1,
                             random_state =7, nthread = -1)

rmse_dt= cross_val_score(dt, train_dummies,train_Y, scoring="neg_mean_squared_error", cv = cv_v,n_jobs=-1)
rmse_rf= cross_val_score(rf, train_dummies,train_Y, scoring="neg_mean_squared_error", cv = cv_v,n_jobs=-1)
rmse_GBoost= cross_val_score(GBoost, train_dummies,train_Y, scoring="neg_mean_squared_error", cv = cv_v,n_jobs=-1)
rmse_model_xgb= cross_val_score(model_xgb, train_dummies,train_Y, scoring="neg_mean_squared_error", cv = cv_v,n_jobs=-1)
# dont put -ve sign for cross val, the o/p of cross val is -ve(for loss and +ve for score) 
#which means small the -ve number, better the model
print(" value for decision tree is {} \n value for random Forest is {} \n \
value for decision GBoost is {}\n value for xgboost is {} \n".format(rmse_dt, rmse_rf,rmse_GBoost,rmse_model_xgb))

In [133]:
def cross_val_score_cv(model, X,Y,scor, cvv=5,njob= -1, withparameters = False):
    """ input 
        model = list of all the models for which we have to do the cross val
        X= independent variables dataframe
        Y = dependent variable series
        cvv = cross validation iteration
        njobs = parallel processing
        withparameters = if True will return the models parameters along with their score else just the name """

    from sklearn.model_selection import cross_val_score
    scores = []
    for name in model:
        score = []
        if withparameters : 
            model_name  = name
        else:
            model_name = type(name)
        score.append(model_name)
        val = cross_val_score(name, X,Y,scoring= scor , cv= cvv, n_jobs= njob)
        score.append(val)
        score.append("Mean score is "+ str(np.mean(val)))
        scores.append(score)

    return scores

In [138]:
rms= cross_val_score_cv([rf], train_dummies,train_Y, scor="neg_mean_squared_error",withparameters=False)

In [139]:
rms

[[sklearn.ensemble.forest.RandomForestRegressor,
  array([-0.02590937, -0.03563975, -0.03447122, -0.02823477, -0.03137543]),
  'Mean score is -0.031126108067030995']]

In [123]:
param_grid = {"max_depth": [3,2,5,6],
              "max_features": ["log2", "sqrt"],
              "min_samples_split": [2, 3, 10],
             # "criterion": ["gini", "entropy"],
              "min_samples_leaf" :[20,30,10]}

In [159]:
grid_search = GridSearchCV(rf, param_grid=param_grid, cv=5,scoring ="neg_mean_squared_error",)
grid_search.fit(train_dummies, train_Y)

GridSearchCV(cv=5, error_score='raise',
       estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=6,
           max_features='sqrt', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=10, min_samples_split=10,
           min_weight_fraction_leaf=0.0, n_estimators=300, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'max_depth': [3, 2, 5, 6], 'max_features': ['log2', 'sqrt'], 'min_samples_split': [2, 3, 10], 'min_samples_leaf': [20, 30, 10]},
       pre_dispatch='2*n_jobs', refit=True,
       scoring='neg_mean_squared_error', verbose=0)

In [160]:
grid_search.best_params_,grid_search.best_score_

({'max_depth': 6,
  'max_features': 'sqrt',
  'min_samples_leaf': 10,
  'min_samples_split': 2},
 -0.031084691490726894)

In [169]:
from sklearn.model_selection import RandomizedSearchCV

In [185]:
from scipy.stats import randint
param_random = {"max_depth": randint(1,20),
              "max_features": ["log2", "sqrt"],
              "min_samples_leaf": randint(5, 50),
              "min_samples_split": randint(5, 50),
              }

In [192]:
random_Search = RandomizedSearchCV(rf,param_distributions=param_random, cv=5,n_iter=20,
                                   scoring ="neg_mean_squared_error")

In [193]:
ran = random_Search.fit(train_dummies,train_Y)

In [194]:
ran.best_estimator_, ran.best_score_, ran.best_params_, ran.n_iter

(RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=15,
            max_features='sqrt', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=6, min_samples_split=20,
            min_weight_fraction_leaf=0.0, n_estimators=300, n_jobs=1,
            oob_score=False, random_state=None, verbose=0, warm_start=False),
 -0.02696214685465325,
 {'max_depth': 15,
  'max_features': 'sqrt',
  'min_samples_leaf': 6,
  'min_samples_split': 20},
 20)

In [196]:
rf1 = RandomForestRegressor(max_depth=15, max_features="sqrt",n_estimators=300,
                           min_samples_leaf=6, min_samples_split=20)
rf2 = RandomForestRegressor(max_depth=6, max_features="sqrt",n_estimators=300,
                           min_samples_leaf=10, min_samples_split=2)

In [199]:
rms1= cross_val_score_cv([rf1], train_dummies,train_Y, scor="neg_mean_squared_error",withparameters=False)
rms2= cross_val_score_cv([rf2], train_dummies,train_Y, scor="neg_mean_squared_error",withparameters=False)

In [202]:
rms1, rms2

([[sklearn.ensemble.forest.RandomForestRegressor,
   array([-0.02175703, -0.03148153, -0.03012285, -0.02375774, -0.02828553]),
   'Mean score is -0.027080934594509047']],
 [[sklearn.ensemble.forest.RandomForestRegressor,
   array([-0.02624206, -0.03543613, -0.03433095, -0.02747743, -0.03230349]),
   'Mean score is -0.03115801342133519']])

In [68]:
import numpy as np
from sklearn.datasets import load_boston
from sklearn.linear_model import RidgeCV
from sklearn.model_selection import cross_val_score

boston = load_boston()
print(cross_val_score(RidgeCV(), boston.data, boston.target, scoring='neg_mean_squared_error'))

[ -19.57152534  -34.18128452 -409.85764986]

In [297]:
dff = pd.DataFrame([[6,2,3,"a"],[3,np.nan,2, np.nan],[3,np.nan,3, np.nan],[3,np.nan,9, np.nan]],
                  index = ["aa","bb","cc","dd"])
dff

    0    1  2    3
aa  6  2.0  3    a
bb  3  NaN  2  NaN
cc  3  NaN  3  NaN
dd  3  NaN  9  NaN

In [281]:
dff.loc[dff[0]>1,[0]] = 5

In [292]:
dff[0] = np.where((dff[0]<5),3,9)

In [303]:
dff.iloc[:,:-1]

    0    1  2
aa  6  2.0  3
bb  3  NaN  2
cc  3  NaN  3
dd  3  NaN  9

In [334]:
from sklearn.feature_extraction import FeatureHasher

dff = pd.DataFrame([[6,2,3,"a"],[3,np.nan,2, "b"],[3,np.nan,3, "a"],[3,np.nan,9, "d"]],
                  index = ["aa","bb","cc","dd"])
dff

    0    1  2  3
aa  6  2.0  3  a
bb  3  NaN  2  b
cc  3  NaN  3  a
dd  3  NaN  9  d

In [335]:
te =  dff[3]
te

aa    a
bb    b
cc    a
dd    d
Name: 3, dtype: object

In [339]:
h = FeatureHasher(n_features=30, input_type='string')

In [340]:
te = h.fit_transform(dff[3])

In [341]:
te.toarray()

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.]])

In [149]:
dic  = {"a":{"b":[2,3,4,], "d":[23,234,234,234,234]}, "v":{"c":["A","b","b"]}}

In [152]:
dic["a"]["b"]

[2, 3, 4]

In [158]:
dic.keys(), dic.values(), dic["a"].keys(), dic["a"].values()

(dict_keys(['a', 'v']),
 dict_values([{'b': [2, 3, 4], 'd': [23, 234, 234, 234, 234]}, {'c': ['A', 'b', 'b']}]),
 dict_keys(['b', 'd']),
 dict_values([[2, 3, 4], [23, 234, 234, 234, 234]]))

In [ ]:
class sklearn.tree.DecisionTreeClassifier(criterion=’gini’, splitter=’best’, max_depth=None, min_samples_split=2, 
                                          min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, 
                                          random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, 
                                          min_impurity_split=None, class_weight=None, presort=False)

class sklearn.tree.DecisionTreeRegressor(criterion=’mse’, splitter=’best’, max_depth=None, min_samples_split=2, 
                                         min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, 
                                         random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, 
                                         min_impurity_split=None, presort=False)

In [ ]:
def parameters_values_regression():